version: '2.1'
services:
  velocity-router:
    image: nginx:1.12
    volumes:
     - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf.template
     - ./conf/ssl/server.crt:/etc/nginx/ssl/server.crt
     - ./conf/ssl/server.key:/etc/nginx/ssl/server.key
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    environment:
      - NGINX_PROTOCOL=${NGINX_PROTOCOL}
      - NGINX_HOST=${NGINX_HOST}
      - NGINX_PORT=${NGINX_PORT}
    command: /bin/bash -c "envsubst '$${NGINX_PROTOCOL},$${NGINX_HOST},$${NGINX_PORT}' < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -c /etc/nginx/conf.d/nginx.conf -g 'daemon off;'"
    links:
      - release-events-ui
      - release-events-api
      - security-api
      - continuous-release-ui
      - multi-app-pipeline-ui
      - multi-app-pipeline-api
      - application-api
      - continuous-release-consumer
      - reporting-sync-api
      - reporting-consumer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  database:
    image:  mongo:3.4
    command: mongod --quiet --logpath=/dev/null
    volumes:
      - mongodb:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  reporting-ui:
    image: ibmcom/velocity-se-reporting-ui:1.0.58
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - database
    environment:
      - ROOT_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reports
      - APP_HOME=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}
      - DDP_DEFAULT_CONNECTION_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reports
      - PORT=80
      - MONGO_URL=mongodb://database:27017/reporting
      - ENCRYPT_KEY=${CIPHER_KEY}
      - ADMIN_PASSWORD=admin
      - DISABLE_SSL=true
      - COMPOSE_VERSION=1.0.1
      - LOG_LEVEL=${LOG_LEVEL}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - SECURITY_AUTH_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api/auth
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - VELOCITY_VERSION=${VELOCITY_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  reporting-consumer:
    image: ibmcom/velocity-se-reporting-consumer:1.0.28
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6004/ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    links:
      - database
    environment:
      - MONGO_URL=mongodb://database:27017/reporting
      - ENCRYPT_KEY=${CIPHER_KEY}
      - CONSUMER_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/reporting-consumer
      - BEARER_TOKEN=${API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  continuous-release-consumer:
    image: ibmcom/velocity-se-continuous-release-consumer:1.0.160
    links:
      - rabbitnode1
    environment:
      - NODE_ENV=onprem
      - PORT=3411
      - API_TOKEN=${API_TOKEN}
      - CIPHER_KEY=${CIPHER_KEY}
      - HMAC_KEY=${HMAC_KEY}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  reporting-sync-api:
    image: ibmcom/velocity-se-reporting-sync-api:1.0.26
    links:
      - rabbitnode1
    environment:
      - NODE_ENV=onprem
      - PORT=3499
      - BEARER_TOKEN=${API_TOKEN}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  application-api:
    image: ibmcom/velocity-se-application-api:1.0.323
    links:
      - database
    environment:
      - DB_TYPE=mongo
      - MONGO_URL=mongodb://database:27017
      - MONGO_DB=application-api
      - NODE_ENV=onprem
      - PORT=3499
      - BEARER_TOKEN=${API_TOKEN}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  release-events-ui:
    image: ibmcom/velocity-se-release-events-ui:1.0.151
    depends_on:
      release-events-api:
        condition: service_started
    environment:
      - NODE_ENV=production
      - PORT=3010
      - LOG_LEVEL=${LOG_LEVEL}
      - release_events_api__host=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/release-events-api
      - security_api__host=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - version=${VELOCITY_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  release-events-api:
    image: ibmcom/velocity-se-release-events-api:1.0.163
    depends_on:
      security-api:
        condition: service_healthy
      multi-app-pipeline-api:
        condition: service_healthy
      reporting-consumer:
        condition: service_healthy
    links:
      - database
      - rabbitnode1
      - continuous-release-ui
      - security-api
      - reporting-consumer
    environment:
      - PORT=8080
      - MONGO_DB=release-events
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URL=mongodb://database:27017
      - SECURITY_API_URL=http://security-api:3911
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - JWT_CIPHER_KEY=${CIPHER_KEY}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - DEPLOY_PLAN_API_URL=http://continuous-release-ui/deploymentPlans
      - DEPLOY_PLAN_API_CIPHER_KEY=${CIPHER_KEY}
      - DEPLOY_PLAN_API_HMAC_KEY=${HMAC_KEY}
      - BEARER_TOKEN=${API_TOKEN}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - MAP_API_URL=http://multi-app-pipeline-api:9090
      - MAP_API_PATH=/v1/multi-app-pipeline
      - MAP_API_TOKEN=${API_TOKEN}
      - ISSUES_API_URL=http://issues-service
      - REPORTING_CONSUMER_API_URL=http://reporting-consumer:6004
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - REPORTING_UI_URL=http://reporting-ui/reports
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  security-api:
    image: ibmcom/velocity-se-security-api:1.0.47
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3911/api/v1/status"]
      interval: 5s
      timeout: 5s
      retries: 10
    links:
      - database
    environment:
      - NODE_ENV=local
      - PORT=3911
      - LOG_LEVEL=${LOG_LEVEL}
      - MONGO_URL=mongodb://database:27017/security
      - MONGO_DB=security
      - TIAM_CLIENT_SECRET=72heYpy2weRih8I3KTxdMVOy90bBpQB0WDY3fH2IixOaAtwnRU
      - BEARER_TOKEN=${API_TOKEN}
      - SECURITY_AUTH_SECRET=${HMAC_KEY}
      - LOGICAL_APP_NAME=security-api
      - BUILD_PREFIX=master
      - JWT_CIPHER_KEY=${CIPHER_KEY}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - ACCESS_KEY=${ACCESS_KEY}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  continuous-release-ui:
    depends_on:
      security-api:
        condition: service_healthy
    image: ibmcom/velocity-se-continuous-release-ui:1.0.133
    links:
      - database
      - rabbitnode1
    environment:
      - PORT=80
      - ROOT_URL=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/deploymentPlans
      - MONGO_URL=mongodb://database:27017/velocity
      - LOG_LEVEL=${LOG_LEVEL}
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
      - APP_API_URL=http://application-api:3499
      - APP_API_AUTH_TOKEN=${API_TOKEN}
      - SECURITY_API_URL=http://security-api:3911/api
      - SECURITY_API_AUTH_TOKEN=${API_TOKEN}
      - REPORTING_CONSUMER_API_URL=http://reporting-consumer:6004
      - REPORTING_CONSUMER_API_AUTH_TOKEN=${API_TOKEN}
      - RELEASE_API_URL=http://release-events-api:8080/graphql
      - RELEASE_API_AUTH_TOKEN=${API_TOKEN}
      - MAP_API_URL=http://multi-app-pipeline-api:9090/v1/multi-app-pipeline/graphql
      - MAP_API_AUTH_TOKEN=${API_TOKEN}
      - JWT_HMAC_KEY=${HMAC_KEY}
      - CR_CIPHER_KEY=${CIPHER_KEY}
      - CR_HMAC_KEY=${HMAC_KEY}
      - CONNECT_URL=http://reporting-consumer:6004
      - CONNECT_TOKEN=${API_TOKEN}
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - AUTH_TOKEN_URL=https://login.ng.bluemix.net/UAALoginServerWAR/oauth/token
      - DRA_API_URL=https://dra.ng.bluemix.net
      - TOOL_CHAINS_URL=https://devops-api.ng.bluemix.net
      - DEVOPS_MESSAGE_STORE_API=https://dlms.ng.bluemix.net
      - |
        METEOR_SETTINGS=
        {
          "public": {
            "requireAuth": true,
            "securityAuthUrl": "${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api/auth",
            "version": "${VELOCITY_VERSION}",
            "features": {
              "SlackTask": false,
              "PipelineV2Task": false,
              "EmailNotifications": true,
              "EmailTask": true,
              "RunAnotherPlanTask": true,
              "Approvals": true,
              "ApprovalTask": true,
              "ServiceNowTask": true,
              "JenkinsTask": true
            }
          }
        }
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  rabbitnode1:
    environment:
      - RABBITMQ_ERLANG_COOKIE='128ad9b8-3d9f-11e8-b467-0ed5f89f718c'
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
      - RABBITMQ_DEFAULT_VHOST=/
    hostname: rabbitnode1
    image: 'rabbitmq:3.6-management'
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    #NOTE Expose ports only for access from outside the cluster.
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbit1:/var/lib/rabbitmq
      - ./conf/rabbit:/etc/rabbitmq/
    command:  bash -c 'sleep 10; rabbitmq-server;'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  multi-app-pipeline-api:
    image: ibmcom/velocity-se-multi-app-pipeline-api:1.0.70
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/v1/multi-app-pipeline/status"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - database
      - security-api
      - continuous-release-ui
    environment:
      - NODE_ENV=container
      - PORT=9090
      - mongo__url=mongodb://database:27017
      - mongo__db=multi-app-pipeline
      - appPath=/v1/multi-app-pipeline
      - authToken=${API_TOKEN}
      - securityApi__url=http://security-api:3911
      - securityApi__auth_secret=${HMAC_KEY}
      - securityApi__token=${API_TOKEN}
      - deployPlanApi__url=http://continuous-release-ui/deploymentPlans
      - deployPlanApi__cipherKey=${CIPHER_KEY}
      - deployPlanApi__hmacKey=${HMAC_KEY}
      - applicationApi__url=http://application-api:3499
      - applicationApi__token=${API_TOKEN}
      - cipher__key=${CIPHER_KEY}
      - hmac__key=${HMAC_KEY}
      - registrationApi__token=${API_TOKEN}
      - integrationApi__token=${API_TOKEN}
      - pipelineApi__cipherKey=${CIPHER_KEY}
      - pipelineApi__hmacKey=${HMAC_KEY}
      - releaseEventsApi__cipherKey=${CIPHER_KEY}
      - releaseEventsApi__hmacKey=${HMAC_KEY}
      - releaseEventsApi__url=http://release-events-api:8080/graphql
      - amqp__enabled=false
      - amqp__host=rabbitnode1
      - amqp__port=5672
      - amqp__path=
      - amqp__user=${RABBITMQ_USER}
      - amqp__password=${RABBITMQ_PASS}
      - amqp__protocol=amqp
      - newRelic__enabled=false
      - redis__enabled=false
      - tunnel__enabled=false
      - serviceProvider__credentials=Y29udF9yZWxlYXNlX3N2Yzp0cDRNQk53TU0y
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  multi-app-pipeline-ui:
    depends_on:
      security-api:
        condition: service_healthy
    links:
      - security-api
      - multi-app-pipeline-api
    image: ibmcom/velocity-se-multi-app-pipeline-ui:1.0.68
    environment:
      - PORT=3030
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - security_api__host=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/security-api
      - redis__enabled=false
      - map_api__frontEndHost=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/multi-app-pipeline-api
      - map_api__host=http://multi-app-pipeline-api:9090
      - map_api__appPath=/v1/multi-app-pipeline
      - deployPlanFrontEndUrl=${NGINX_PROTOCOL}://${NGINX_HOST}:${NGINX_PORT}/deploymentPlans
      - version=${VELOCITY_VERSION}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  issues-service:
    depends_on:
      security-api:
        condition: service_healthy
    image: ibmcom/velocity-se-issues_service:1.0.78
    environment:
      - MONGO_DB=issue-tracking
      - MONGO_URL=mongodb://database:27017
      - BEARER_TOKEN=${API_TOKEN}
      - PORT=80
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

  continuous-release-poller:
    links:
      - application-api
    image: ibmcom/velocity-se-continuous-release-poller:1.0.13
    environment:
      - MONGO_URL=mongodb://database:27017/velocity
      - APP_API_TOKEN=${API_TOKEN}
      - APP_API_URL=http://application-api:3499
      - NODE_ENV=prod
      - AMQP_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitnode1:5672/
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"

volumes:
  mongodb:
    driver: local
  rabbit1:
    driver: local
